# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zz/data_structure_specialized_pratice

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zz/data_structure_specialized_pratice

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zz/data_structure_specialized_pratice/CMakeFiles /home/zz/data_structure_specialized_pratice//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zz/data_structure_specialized_pratice/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named data_structure_specialized_pratice

# Build rule for target.
data_structure_specialized_pratice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data_structure_specialized_pratice
.PHONY : data_structure_specialized_pratice

# fast build rule for target.
data_structure_specialized_pratice/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/build
.PHONY : data_structure_specialized_pratice/fast

buffer.o: buffer.cpp.o
.PHONY : buffer.o

# target to build an object file
buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/buffer.cpp.o
.PHONY : buffer.cpp.o

buffer.i: buffer.cpp.i
.PHONY : buffer.i

# target to preprocess a source file
buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/buffer.cpp.i
.PHONY : buffer.cpp.i

buffer.s: buffer.cpp.s
.PHONY : buffer.s

# target to generate assembly for a file
buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/buffer.cpp.s
.PHONY : buffer.cpp.s

k_way_merge_test.o: k_way_merge_test.cpp.o
.PHONY : k_way_merge_test.o

# target to build an object file
k_way_merge_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/k_way_merge_test.cpp.o
.PHONY : k_way_merge_test.cpp.o

k_way_merge_test.i: k_way_merge_test.cpp.i
.PHONY : k_way_merge_test.i

# target to preprocess a source file
k_way_merge_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/k_way_merge_test.cpp.i
.PHONY : k_way_merge_test.cpp.i

k_way_merge_test.s: k_way_merge_test.cpp.s
.PHONY : k_way_merge_test.s

# target to generate assembly for a file
k_way_merge_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/k_way_merge_test.cpp.s
.PHONY : k_way_merge_test.cpp.s

k_way_merge_threads.o: k_way_merge_threads.cpp.o
.PHONY : k_way_merge_threads.o

# target to build an object file
k_way_merge_threads.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/k_way_merge_threads.cpp.o
.PHONY : k_way_merge_threads.cpp.o

k_way_merge_threads.i: k_way_merge_threads.cpp.i
.PHONY : k_way_merge_threads.i

# target to preprocess a source file
k_way_merge_threads.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/k_way_merge_threads.cpp.i
.PHONY : k_way_merge_threads.cpp.i

k_way_merge_threads.s: k_way_merge_threads.cpp.s
.PHONY : k_way_merge_threads.s

# target to generate assembly for a file
k_way_merge_threads.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/k_way_merge_threads.cpp.s
.PHONY : k_way_merge_threads.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/main.cpp.s
.PHONY : main.cpp.s

merge_plan.o: merge_plan.cpp.o
.PHONY : merge_plan.o

# target to build an object file
merge_plan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/merge_plan.cpp.o
.PHONY : merge_plan.cpp.o

merge_plan.i: merge_plan.cpp.i
.PHONY : merge_plan.i

# target to preprocess a source file
merge_plan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/merge_plan.cpp.i
.PHONY : merge_plan.cpp.i

merge_plan.s: merge_plan.cpp.s
.PHONY : merge_plan.s

# target to generate assembly for a file
merge_plan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/merge_plan.cpp.s
.PHONY : merge_plan.cpp.s

merge_plan_tree_test.o: merge_plan_tree_test.cpp.o
.PHONY : merge_plan_tree_test.o

# target to build an object file
merge_plan_tree_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/merge_plan_tree_test.cpp.o
.PHONY : merge_plan_tree_test.cpp.o

merge_plan_tree_test.i: merge_plan_tree_test.cpp.i
.PHONY : merge_plan_tree_test.i

# target to preprocess a source file
merge_plan_tree_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/merge_plan_tree_test.cpp.i
.PHONY : merge_plan_tree_test.cpp.i

merge_plan_tree_test.s: merge_plan_tree_test.cpp.s
.PHONY : merge_plan_tree_test.s

# target to generate assembly for a file
merge_plan_tree_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/merge_plan_tree_test.cpp.s
.PHONY : merge_plan_tree_test.cpp.s

multi_run_file.o: multi_run_file.cpp.o
.PHONY : multi_run_file.o

# target to build an object file
multi_run_file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/multi_run_file.cpp.o
.PHONY : multi_run_file.cpp.o

multi_run_file.i: multi_run_file.cpp.i
.PHONY : multi_run_file.i

# target to preprocess a source file
multi_run_file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/multi_run_file.cpp.i
.PHONY : multi_run_file.cpp.i

multi_run_file.s: multi_run_file.cpp.s
.PHONY : multi_run_file.s

# target to generate assembly for a file
multi_run_file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/multi_run_file.cpp.s
.PHONY : multi_run_file.cpp.s

multi_thread_test.o: multi_thread_test.cpp.o
.PHONY : multi_thread_test.o

# target to build an object file
multi_thread_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/multi_thread_test.cpp.o
.PHONY : multi_thread_test.cpp.o

multi_thread_test.i: multi_thread_test.cpp.i
.PHONY : multi_thread_test.i

# target to preprocess a source file
multi_thread_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/multi_thread_test.cpp.i
.PHONY : multi_thread_test.cpp.i

multi_thread_test.s: multi_thread_test.cpp.s
.PHONY : multi_thread_test.s

# target to generate assembly for a file
multi_thread_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/multi_thread_test.cpp.s
.PHONY : multi_thread_test.cpp.s

run_store.o: run_store.cpp.o
.PHONY : run_store.o

# target to build an object file
run_store.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/run_store.cpp.o
.PHONY : run_store.cpp.o

run_store.i: run_store.cpp.i
.PHONY : run_store.i

# target to preprocess a source file
run_store.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/run_store.cpp.i
.PHONY : run_store.cpp.i

run_store.s: run_store.cpp.s
.PHONY : run_store.s

# target to generate assembly for a file
run_store.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/run_store.cpp.s
.PHONY : run_store.cpp.s

threads.o: threads.cpp.o
.PHONY : threads.o

# target to build an object file
threads.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/threads.cpp.o
.PHONY : threads.cpp.o

threads.i: threads.cpp.i
.PHONY : threads.i

# target to preprocess a source file
threads.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/threads.cpp.i
.PHONY : threads.cpp.i

threads.s: threads.cpp.s
.PHONY : threads.s

# target to generate assembly for a file
threads.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/threads.cpp.s
.PHONY : threads.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... data_structure_specialized_pratice"
	@echo "... buffer.o"
	@echo "... buffer.i"
	@echo "... buffer.s"
	@echo "... k_way_merge_test.o"
	@echo "... k_way_merge_test.i"
	@echo "... k_way_merge_test.s"
	@echo "... k_way_merge_threads.o"
	@echo "... k_way_merge_threads.i"
	@echo "... k_way_merge_threads.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... merge_plan.o"
	@echo "... merge_plan.i"
	@echo "... merge_plan.s"
	@echo "... merge_plan_tree_test.o"
	@echo "... merge_plan_tree_test.i"
	@echo "... merge_plan_tree_test.s"
	@echo "... multi_run_file.o"
	@echo "... multi_run_file.i"
	@echo "... multi_run_file.s"
	@echo "... multi_thread_test.o"
	@echo "... multi_thread_test.i"
	@echo "... multi_thread_test.s"
	@echo "... run_store.o"
	@echo "... run_store.i"
	@echo "... run_store.s"
	@echo "... threads.o"
	@echo "... threads.i"
	@echo "... threads.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

