# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zz/data_structure_specialized_pratice

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zz/data_structure_specialized_pratice

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zz/data_structure_specialized_pratice/CMakeFiles /home/zz/data_structure_specialized_pratice//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zz/data_structure_specialized_pratice/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named data_structure_specialized_pratice

# Build rule for target.
data_structure_specialized_pratice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data_structure_specialized_pratice
.PHONY : data_structure_specialized_pratice

# fast build rule for target.
data_structure_specialized_pratice/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/build
.PHONY : data_structure_specialized_pratice/fast

src/Buffer.o: src/Buffer.cpp.o
.PHONY : src/Buffer.o

# target to build an object file
src/Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/Buffer.cpp.o
.PHONY : src/Buffer.cpp.o

src/Buffer.i: src/Buffer.cpp.i
.PHONY : src/Buffer.i

# target to preprocess a source file
src/Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/Buffer.cpp.i
.PHONY : src/Buffer.cpp.i

src/Buffer.s: src/Buffer.cpp.s
.PHONY : src/Buffer.s

# target to generate assembly for a file
src/Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/Buffer.cpp.s
.PHONY : src/Buffer.cpp.s

src/FileHelper.o: src/FileHelper.cpp.o
.PHONY : src/FileHelper.o

# target to build an object file
src/FileHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/FileHelper.cpp.o
.PHONY : src/FileHelper.cpp.o

src/FileHelper.i: src/FileHelper.cpp.i
.PHONY : src/FileHelper.i

# target to preprocess a source file
src/FileHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/FileHelper.cpp.i
.PHONY : src/FileHelper.cpp.i

src/FileHelper.s: src/FileHelper.cpp.s
.PHONY : src/FileHelper.s

# target to generate assembly for a file
src/FileHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/FileHelper.cpp.s
.PHONY : src/FileHelper.cpp.s

src/MergeSortFile.o: src/MergeSortFile.cpp.o
.PHONY : src/MergeSortFile.o

# target to build an object file
src/MergeSortFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/MergeSortFile.cpp.o
.PHONY : src/MergeSortFile.cpp.o

src/MergeSortFile.i: src/MergeSortFile.cpp.i
.PHONY : src/MergeSortFile.i

# target to preprocess a source file
src/MergeSortFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/MergeSortFile.cpp.i
.PHONY : src/MergeSortFile.cpp.i

src/MergeSortFile.s: src/MergeSortFile.cpp.s
.PHONY : src/MergeSortFile.s

# target to generate assembly for a file
src/MergeSortFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/MergeSortFile.cpp.s
.PHONY : src/MergeSortFile.cpp.s

src/TwoWayMerger.o: src/TwoWayMerger.cpp.o
.PHONY : src/TwoWayMerger.o

# target to build an object file
src/TwoWayMerger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/TwoWayMerger.cpp.o
.PHONY : src/TwoWayMerger.cpp.o

src/TwoWayMerger.i: src/TwoWayMerger.cpp.i
.PHONY : src/TwoWayMerger.i

# target to preprocess a source file
src/TwoWayMerger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/TwoWayMerger.cpp.i
.PHONY : src/TwoWayMerger.cpp.i

src/TwoWayMerger.s: src/TwoWayMerger.cpp.s
.PHONY : src/TwoWayMerger.s

# target to generate assembly for a file
src/TwoWayMerger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/TwoWayMerger.cpp.s
.PHONY : src/TwoWayMerger.cpp.s

src/data_structure_specialized_pratice.o: src/data_structure_specialized_pratice.cpp.o
.PHONY : src/data_structure_specialized_pratice.o

# target to build an object file
src/data_structure_specialized_pratice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/data_structure_specialized_pratice.cpp.o
.PHONY : src/data_structure_specialized_pratice.cpp.o

src/data_structure_specialized_pratice.i: src/data_structure_specialized_pratice.cpp.i
.PHONY : src/data_structure_specialized_pratice.i

# target to preprocess a source file
src/data_structure_specialized_pratice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/data_structure_specialized_pratice.cpp.i
.PHONY : src/data_structure_specialized_pratice.cpp.i

src/data_structure_specialized_pratice.s: src/data_structure_specialized_pratice.cpp.s
.PHONY : src/data_structure_specialized_pratice.s

# target to generate assembly for a file
src/data_structure_specialized_pratice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/data_structure_specialized_pratice.cpp.s
.PHONY : src/data_structure_specialized_pratice.cpp.s

src/testExternalMergeSort.o: src/testExternalMergeSort.cpp.o
.PHONY : src/testExternalMergeSort.o

# target to build an object file
src/testExternalMergeSort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/testExternalMergeSort.cpp.o
.PHONY : src/testExternalMergeSort.cpp.o

src/testExternalMergeSort.i: src/testExternalMergeSort.cpp.i
.PHONY : src/testExternalMergeSort.i

# target to preprocess a source file
src/testExternalMergeSort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/testExternalMergeSort.cpp.i
.PHONY : src/testExternalMergeSort.cpp.i

src/testExternalMergeSort.s: src/testExternalMergeSort.cpp.s
.PHONY : src/testExternalMergeSort.s

# target to generate assembly for a file
src/testExternalMergeSort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/testExternalMergeSort.cpp.s
.PHONY : src/testExternalMergeSort.cpp.s

src/testGenRun.o: src/testGenRun.cpp.o
.PHONY : src/testGenRun.o

# target to build an object file
src/testGenRun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/testGenRun.cpp.o
.PHONY : src/testGenRun.cpp.o

src/testGenRun.i: src/testGenRun.cpp.i
.PHONY : src/testGenRun.i

# target to preprocess a source file
src/testGenRun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/testGenRun.cpp.i
.PHONY : src/testGenRun.cpp.i

src/testGenRun.s: src/testGenRun.cpp.s
.PHONY : src/testGenRun.s

# target to generate assembly for a file
src/testGenRun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/testGenRun.cpp.s
.PHONY : src/testGenRun.cpp.s

src/testMergeInMem.o: src/testMergeInMem.cpp.o
.PHONY : src/testMergeInMem.o

# target to build an object file
src/testMergeInMem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/testMergeInMem.cpp.o
.PHONY : src/testMergeInMem.cpp.o

src/testMergeInMem.i: src/testMergeInMem.cpp.i
.PHONY : src/testMergeInMem.i

# target to preprocess a source file
src/testMergeInMem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/testMergeInMem.cpp.i
.PHONY : src/testMergeInMem.cpp.i

src/testMergeInMem.s: src/testMergeInMem.cpp.s
.PHONY : src/testMergeInMem.s

# target to generate assembly for a file
src/testMergeInMem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_specialized_pratice.dir/build.make CMakeFiles/data_structure_specialized_pratice.dir/src/testMergeInMem.cpp.s
.PHONY : src/testMergeInMem.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... data_structure_specialized_pratice"
	@echo "... src/Buffer.o"
	@echo "... src/Buffer.i"
	@echo "... src/Buffer.s"
	@echo "... src/FileHelper.o"
	@echo "... src/FileHelper.i"
	@echo "... src/FileHelper.s"
	@echo "... src/MergeSortFile.o"
	@echo "... src/MergeSortFile.i"
	@echo "... src/MergeSortFile.s"
	@echo "... src/TwoWayMerger.o"
	@echo "... src/TwoWayMerger.i"
	@echo "... src/TwoWayMerger.s"
	@echo "... src/data_structure_specialized_pratice.o"
	@echo "... src/data_structure_specialized_pratice.i"
	@echo "... src/data_structure_specialized_pratice.s"
	@echo "... src/testExternalMergeSort.o"
	@echo "... src/testExternalMergeSort.i"
	@echo "... src/testExternalMergeSort.s"
	@echo "... src/testGenRun.o"
	@echo "... src/testGenRun.i"
	@echo "... src/testGenRun.s"
	@echo "... src/testMergeInMem.o"
	@echo "... src/testMergeInMem.i"
	@echo "... src/testMergeInMem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

